### ISSUE TITLE
Python CDK support broken due to module name

### ISSUE THREAD

**Issue by jpxd** [RenovoSolutions/cdk-library-certbot#88]
**Describe the bug**
Thanks for this cool construct! We use CDK with python and since you also published your construct to [Pypi](https://pypi.org/project/renovosolutions.aws-cdk-certbot/), we thought it is already usable. When trying to synth or deploy there is a syntax error in your module when trying to import the `one-time-event` module. Dashes are not allowed in python identifiers. Is the one-time-event module really necessary here?

```
(.venv) ➜  Test git:(master) ✗ cdk deploy --all
Traceback (most recent call last):
  File "app.py", line 3, in <module>
    from test.test_stack import TestStack
  File "/Users/test/Projects/Test/test/test/test_stack", line 13, in <module>
    from certbot import Certbot
  File "/Users/test/Projects/Test/.venv/lib/python3.8/site-packages/certbot/__init__.py", line 64, in <module>
    from ._jsii import *
  File "/Users/test/Projects/Test/.venv/lib/python3.8/site-packages/certbot/_jsii/__init__.py", line 21
    import one-time-event._jsii
              ^
SyntaxError: invalid syntax
Subprocess exited with error 1
```

**To Reproduce**
1. `mkdir test `
2. `cd test`
3. `cdk init app --language python   `
4. `source .venv/bin/activate`
5. Add `renovosolutions.aws-cdk-certbot==0.1.36` to requirements.txt
6. `python -m pip install -r requirements.txt`
7. Add `import certbot` and `x = certbot.Certbot(self, 'Certbot', {})` to test_stack.py
8. `cdk synth`

**Expected behavior**
No error.

**Comment by bmiller08** [comment]
The one-time-event module is used to generate an event schedule that occurs only one time shortly after deployment. This allows the certs to be created immediately. I will look at this bug and try to resolve. I also maintain and publish the one-time-event module so should not be a huge issue.

**Comment by bmiller08** [comment]
I was able to resolve the import error, but getting other errors now about missing keyword arguments. I'll try to take a look deeper and see whats happening. That part is automatically determined by JSII so I am not sure why the properties aren't working when using the class.

I'll try to look deeper soon.

**Comment by bmiller08** [comment]
Python library should now work completely as of https://github.com/RenovoSolutions/cdk-library-certbot/pull/101. It turns out I was creating the properties interface in a way that did not convert to python in a clean manner. You will want to specify `0.2.0` or newer in your `requirements.txt` and something like the following should work:

```
from aws_cdk import (
    core as cdk
)
from certbot import Certbot

# For consistency with other languages, `cdk` is the preferred import name for
# the CDK's core module.  The following line also imports it as `core` for use
# with examples from the CDK Developer's Guide, which are in the process of
# being updated to use `cdk`.  You may delete this import if you don't need it.
from aws_cdk import core


class CertbotTestStack(cdk.Stack):

    def __init__(self, scope: cdk.Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        Certbot(self, "certbot",
            letsencrypt_email="webmaster@example.com",
            letsencrypt_domains="example.com",
            hosted_zone_names=["example.com"]
        )
```

This example has also been added to the README. I appreciate you reporting this issue.
