### ISSUE TITLE
Push to Secret Manager

### ISSUE THREAD

**Issue by CarsonF** [RenovoSolutions/cdk-library-certbot#881]
**Is your feature request related to a problem? Please describe.**
Currently I can't get the cert info to pass to ECS Fargate service.

**Describe the solution you'd like**
If it was stored in secret manager then it could be passed natively that way.

**Comment by ClaudiuCeia** [comment]
Can we reopen this? I would also need the cert available in an ECS service and I have no clean way to pass it from S3 (this is a service image based on public docker image that I don't control). Having it available in Secret Manager would allow passing the key and cert as a secret env var when provisioning ECS.

**Comment by bmiller08** [comment]
Reopened. I'll take a look.

**Comment by bmiller08** [comment]
This has been implemented https://github.com/RenovoSolutions/cdk-library-certbot/releases/tag/v2.5.0

**Comment by ClaudiuCeia** [comment]
> This has been implemented https://github.com/RenovoSolutions/cdk-library-certbot/releases/tag/v2.5.0

That was quick - thanks @bmiller08!
