### ISSUE TITLE
Resource handler returned message: Resource /my/secret/path/* must be in ARN format or "*". 

### ISSUE THREAD

**Issue by gabotechs** [RenovoSolutions/cdk-library-certbot#905]
I am trying to use the `secretsmanager` certificate storage, but the stack fails to create with the following error:

```
❌  MyStack failed: Error: The stack named MyStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "Resource /my/secret/path/* must be in ARN format or "*". (Service: Iam, Status Code: 400)"
```

**Comment by bmiller08** [comment]
> I am trying to use the `secretsmanager` certificate storage, but the stack fails to create with the following error:
> 
> ```
> ❌  MyStack failed: Error: The stack named MyStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "Resource /my/secret/path/* must be in ARN format or "*". (Service: Iam, Status Code: 400)"
> ```

You may have already moved on from this but if you can provide a code example of your stack I can look at why this might occur
