### ISSUE TITLE
Incorrect policy setup for SSM/SecretsManager storage option

### ISSUE THREAD

**Issue by hanchri** [RenovoSolutions/cdk-library-certbot#906]
The current policy setup for both the SSM and SecretsManager storage option in storage-helpers.ts are incorrect (see also  #905): the "resource" array relies on the secretsManagerPath/parameterStorePath properties, which are either externally provided or default to "/certbot/certificates/${props.letsencryptDomains.split(',')[0]}/". This is not resulting in a valid ARN, causing failures of the form "Resource handler returned message: "Resource <path-provided>/* must be in ARN format or "*". (Service: Iam, Status Code: 400)".

**Comment by bmiller08** [comment]
Thanks for the issue. I'll take a look as soon as I can.

**Comment by bmiller08** [comment]
This should be resolved in #907 and released in `2.5.1` available now.
