### ISSUE TITLE
I want to be able to change the architecture of the lambda function.

### ISSUE THREAD

**Issue by eternity1984** [RenovoSolutions/cdk-library-certbot#913]
**Is your feature request related to a problem? Please describe.**
I use an Apple silicon MacBook.
An error occurred when I ran the deployed function. This is likely due to Certbot using an arm64-based Python 3.10 image for building, while the deployment environment runs on the x86_64 architecture.

```json
{
  "errorMessage": "Unable to import module 'index': /var/task/cryptography/hazmat/bindings/_rust.abi3.so: cannot open shared object file: No such file or directory",
  "errorType": "Runtime.ImportModuleError",
  "requestId": "",
  "stackTrace": []
}
```

**Describe the solution you'd like**
I want it to be deployed and ready to go.

**Describe alternatives you've considered**
I manually change the architecture to arm64 and re-upload the built code, it works.

**Additional context**

**Proposed implementation**
Makes architecture parameters configurable.

```diff
@@ -254,6 +254,7 @@ export class Certbot extends Construct {
     this.handler = new lambda.Function(this, 'handler', {
       runtime: lambda.Runtime.PYTHON_3_10,
       role,
+      architecture: props.architecture || lambda.Architecture.X86_64,
       code: lambda.Code.fromAsset(functionDir, {
         bundling: {
           image: lambda.Runtime.PYTHON_3_10.bundlingImage,
```

```typescript
const certbot = new Certbot(this, "Certbot", {
  functionName: functionName,
  letsencryptDomains: zoneName,
  letsencryptEmail: "le@domain.tld",
  hostedZones: [publicHostedZone],
  certificateStorage: CertificateStorageType.SECRETS_MANAGER,
  architecture: lambda.Architecture.ARM_64,
});
```
**Any currently forseeable downsides to this approach**

**Comment by bmiller08** [comment]
Resolved as part of [2.8.0](https://github.com/RenovoSolutions/cdk-library-certbot/releases/tag/v2.8.0):
npm: https://www.npmjs.com/package/@renovosolutions/cdk-library-certbot/v/2.8.0
pypi: https://pypi.org/project/renovosolutions.aws-cdk-certbot/2.8.0/
